#!/usr/bin/env python3
"""
generate_repo_txt.py

1. Clears all cell outputs (and execution counts) from every .ipynb file in
   the repository so that large/noisy outputs are removed.
2. Collects the raw text of every file in the repository (excluding .git,
   __pycache__, .ipynb_checkpoints, and the output files themselves) and
   writes them into one or more plain-text files, each no larger than 2 MB.

Output files are named  repo_content_part1.txt, repo_content_part2.txt, ...
and are placed in the repository root.
"""

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
MAX_BYTES = 2 * 1024 * 1024          # 2 MB per output file
OUTPUT_PREFIX = "repo_content_part"
OUTPUT_SUFFIX = ".txt"

# Directories / path fragments to skip entirely
SKIP_DIRS = {".git", "__pycache__", ".ipynb_checkpoints"}
# Prefixes of the output files we generate (so we never include them in themselves)
OUTPUT_PATTERN = OUTPUT_PREFIX


# ── helpers ────────────────────────────────────────────────────────────────────

def should_skip(path: str) -> bool:
    """Return True if this path should be excluded from collection."""
    rel = os.path.relpath(path, REPO_ROOT)
    parts = rel.split(os.sep)
    # skip hidden / special dirs
    for part in parts:
        if part in SKIP_DIRS:
            return True
    # skip this script itself and previously generated output files
    basename = os.path.basename(path)
    if basename == os.path.basename(__file__):
        return True
    if basename.startswith(OUTPUT_PATTERN) and basename.endswith(OUTPUT_SUFFIX):
        return True
    return False


def clear_notebook_outputs(nb_path: str) -> bool:
    """
    Remove outputs and reset execution_count for every cell in a notebook.
    Returns True if the file was modified.
    """
    with open(nb_path, "r", encoding="utf-8", errors="replace") as fh:
        try:
            nb = json.load(fh)
        except json.JSONDecodeError:
            return False

    modified = False
    for cell in nb.get("cells", []):
        if cell.get("outputs"):
            cell["outputs"] = []
            modified = True
        if cell.get("execution_count") is not None:
            cell["execution_count"] = None
            modified = True

    if modified:
        with open(nb_path, "w", encoding="utf-8") as fh:
            json.dump(nb, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
        print(f"  [cleared] {os.path.relpath(nb_path, REPO_ROOT)}")

    return modified


# ── step 1 : clear notebook outputs ───────────────────────────────────────────

print("=== Step 1: Clearing notebook cell outputs ===")
nb_count = 0
for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
    # prune skipped dirs in-place so os.walk doesn't descend into them
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for filename in filenames:
        if filename.endswith(".ipynb"):
            full = os.path.join(dirpath, filename)
            if clear_notebook_outputs(full):
                nb_count += 1

print(f"  Cleared outputs in {nb_count} notebook(s).\n")


# ── step 2 : collect all file contents ────────────────────────────────────────

print("=== Step 2: Collecting repository content ===")

# Gather sorted list of files
all_files = []
for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for filename in sorted(filenames):
        full = os.path.join(dirpath, filename)
        if not should_skip(full):
            all_files.append(full)

all_files.sort()

# Write content into ≤2 MB chunks
part = 1
current_size = 0
out_fh = None

SEPARATOR = "=" * 72 + "\n"


def open_part(n: int):
    name = os.path.join(REPO_ROOT, f"{OUTPUT_PREFIX}{n}{OUTPUT_SUFFIX}")
    fh = open(name, "w", encoding="utf-8")
    header = (
        f"# Repository content dump – part {n}\n"
        f"# Generated by generate_repo_txt.py\n"
        + SEPARATOR
    )
    fh.write(header)
    return fh, len(header.encode("utf-8"))


out_fh, current_size = open_part(part)

for filepath in all_files:
    rel = os.path.relpath(filepath, REPO_ROOT)
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
            content = fh.read()
    except Exception as exc:
        content = f"<could not read file: {exc}>\n"

    file_header = f"\n### FILE: {rel}\n" + SEPARATOR
    block = file_header + content + "\n"
    block_bytes = block.encode("utf-8")

    # If this single block is larger than MAX_BYTES, split it into chunks
    if len(block_bytes) > MAX_BYTES:
        # Write what fits in the current part, then overflow into new parts
        remaining = block_bytes
        # write the file header first
        header_bytes = file_header.encode("utf-8")
        if current_size + len(header_bytes) > MAX_BYTES:
            out_fh.close()
            part += 1
            out_fh, current_size = open_part(part)
        out_fh.write(file_header)
        current_size += len(header_bytes)
        remaining = (content + "\n").encode("utf-8")

        chunk_size = MAX_BYTES - 200   # leave a small margin
        offset = 0
        while offset < len(remaining):
            chunk = remaining[offset: offset + chunk_size]
            chunk_str = chunk.decode("utf-8", errors="replace")
            if current_size + len(chunk) > MAX_BYTES:
                out_fh.close()
                part += 1
                out_fh, current_size = open_part(part)
            out_fh.write(chunk_str)
            current_size += len(chunk)
            offset += chunk_size
    else:
        if current_size + len(block_bytes) > MAX_BYTES:
            out_fh.close()
            part += 1
            out_fh, current_size = open_part(part)
        out_fh.write(block)
        current_size += len(block_bytes)

out_fh.close()
print(f"  Written {part} output file(s).")
print("\nDone.")
